package com.pg.webapp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class KpiListWindow extends Panel {
	protected VerticalLayout kpiSelectionContainer;
	protected Label titleLabel;
	protected VerticalLayout kpiListContainer;
	protected HorizontalLayout formulaContainer;
	protected TextArea formulaArea;
	protected FormLayout buttonsContainer;

	public KpiListWindow() {
		Design.read(this);
	}
}
