package com.pg.webapp;

import com.sun.nio.sctp.Notification;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;


@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Test extends VerticalLayout {
	protected TextField path;
	protected TextField newpath;
	protected Button submit;

	
	public Test() {
		Design.read(this);
		submit.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				getUI().getCurrent().showNotification("button clicked");	
			}
		});
	}
}
