package com.pg.webapp.counter_management;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class New_KPI_Window_2 extends HorizontalLayout {
	protected VerticalLayout newKpiContainer2;
	protected HorizontalLayout technology_hl;
	protected Label technology_label;
	protected Label technology_label_value;
	protected VerticalLayout code_vl;
	protected Label aggregations_label;
	protected CheckBox cellCode_CB;
	protected CheckBox siteCode_CB;
	protected CheckBox bscCode_CB;
	protected HorizontalLayout kpi_name_hl;
	protected TextField kpi_Name;
	protected CheckBox dynamic_thresholding;
	protected HorizontalLayout formulabar_hl;
	protected TextArea formula_Area;
	protected NativeButton addButton;
	protected ComboBox counters_ComboBox;
	protected HorizontalLayout buttons_hl;
	protected NativeButton saveButton;
	protected NativeButton validateButton;

	public New_KPI_Window_2() {
		Design.read(this);
	}
}
