package com.pg.webapp.counter_management;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class New_KPI_Window extends VerticalLayout {
	protected VerticalLayout new_Kpi_Container;
	protected TabSheet new_kpi_tabsheet;
	protected VerticalLayout new_kpi_vl1;
	protected GridLayout new_kpi_gridLayout1;
	protected NativeButton create_kpi_btn1;
	protected VerticalLayout new_kpi_vl2;
	protected GridLayout new_kpi_gridLayout2;
	protected NativeButton create_kpi_btn2;
	protected VerticalLayout new_kpi_vl3;
	protected GridLayout new_kpi_gridLayout3;
	protected NativeButton create_kpi_btn3;
	protected VerticalLayout new_kpi_vl4;
	protected GridLayout new_kpi_gridLayout4;
	protected NativeButton create_kpi_btn4;
	protected VerticalLayout new_kpi_vl5;
	protected GridLayout new_kpi_gridLayout5;
	protected NativeButton create_kpi_btn5;

	public New_KPI_Window() {
		Design.read(this);
	}
}
